// 엄청 많이 추가 가능!
const BIG_FONT_LIST = [
    "'Sansita One', cursive",
    "'Ribeye Marrow', cursive",
    "'Bebas Neue', sans-serif",
    "'Rubik Moonrocks', cursive",
    "'Rubik 80s Fade', cursive",
    "'Rubik Bubbles', cursive",
    "'Rubik Vinyl', cursive",
    "'Scope One', serif",
    "'Splash', cursive",
    "'Pacifico', cursive",
    "'Luckiest Guy', cursive",
    "'Satisfy', cursive",
    "'Fredoka One', cursive",
    "'Orbitron', sans-serif",
    "'Monoton', cursive",
    "'Anton', sans-serif",
    "'Black Ops One', cursive",
    "'Press Start 2P', cursive",
    "'Permanent Marker', cursive",
    "'Lobster', cursive",
    // Modern & Popular Fonts
    "'Poppins', sans-serif",
    "'Roboto', sans-serif",
    "'Open Sans', sans-serif",
    "'Lato', sans-serif",
    "'Montserrat', sans-serif",
    "'Inter', sans-serif",
    "'Playfair Display', serif",
    "'Source Sans Pro', sans-serif",
    "'Raleway', sans-serif",
    "'Oswald', sans-serif",
    "'Noto Sans', sans-serif",
    "'Ubuntu', sans-serif",
    "'Roboto Condensed', sans-serif",
    "'Roboto Mono', monospace",
    "'DM Sans', sans-serif",
    "'Work Sans', sans-serif",
    "'Nunito', sans-serif",
    "'Quicksand', sans-serif",
    "'Josefin Sans', sans-serif",
    "'Merriweather', serif",
    "'PT Sans', sans-serif",
    "'Lora', serif",
    "'Fira Sans', sans-serif",
    "'Mukta', sans-serif",
    "'Noto Serif', serif",
    "'Inconsolata', monospace",
    "'Source Code Pro', monospace",
    "'Dancing Script', cursive",
    "'Crimson Text', serif",
    "'Karla', sans-serif",
    "'Bitter', serif",
    "'Libre Franklin', sans-serif",
    "'Arimo', sans-serif",
    "'Libre Baskerville', serif",
    "'Space Grotesk', sans-serif",
    "'Manrope', sans-serif",
    "'IBM Plex Sans', sans-serif",
    "'Barlow', sans-serif",
    "'Mulish', sans-serif",
    "'Nanum Gothic', sans-serif",
    "'Titillium Web', sans-serif",
    "'Prompt', sans-serif",
    "'Comfortaa', cursive",
    "'Kanit', sans-serif",
    "'Exo 2', sans-serif",
    "'Overpass', sans-serif",
    "'Cabin', sans-serif",
    "'Catamaran', sans-serif",
    "'Heebo', sans-serif",
    "'Assistant', sans-serif",
    "'Archivo', sans-serif",
    "'Spectral', serif",
    "'Cormorant Garamond', serif",
    "'Alegreya', serif",
    "'Alegreya Sans', sans-serif",
    "'Sora', sans-serif",
    "'Figtree', sans-serif",
    "'Plus Jakarta Sans', sans-serif",
    "'Urbanist', sans-serif",
    "'Lexend', sans-serif",
    "'Epilogue', sans-serif",
    "'Syne', sans-serif",
    "'Albert Sans', sans-serif",
    "'Instrument Sans', sans-serif",
    "'Bricolage Grotesque', sans-serif",
    "'Inclusive Sans', sans-serif",
    "'Onest', sans-serif",
    "'Familjen Grotesk', sans-serif",
    "'Unbounded', sans-serif",
    "'Chivo', sans-serif",
    "'Fraunces', serif",
    "'Newsreader', serif",
    "'Literata', serif",
    "'Petrona', serif",
    "'Piazzolla', serif",
    "'Texturina', serif",
    "'Brygada 1918', serif",
    "'Crimson Pro', serif",
    "'Anybody', sans-serif",
    "'Spline Sans', sans-serif",
    "'Readex Pro', sans-serif",
    "'Noto Sans Display', sans-serif",
    "'Noto Serif Display', serif",
    "'Azeret Mono', monospace",
    "'JetBrains Mono', monospace",
    "'Space Mono', monospace",
    "'Red Hat Mono', monospace",
    "'Anonymous Pro', monospace",
    "'Fira Code', monospace",
    "'Share Tech Mono', monospace",
    "'Overpass Mono', monospace",
    "'IBM Plex Mono', monospace",
    "'Cousine', monospace",
    "'Oxygen Mono', monospace",
    "'Nova Mono', monospace",
    "'Cutive Mono', monospace",
    "'VT323', monospace",
];

export default BIG_FONT_LIST;
